Repository aqden/datahub, pull requests merged in 2023-09, with the labels that each got.

#118 fix(kafka-setup): workaround for pyyaml dependencies in kafka-setup
  docker/kafka-setup/Dockerfile
  docker/quickstart/generate_and_compare.sh
  docker/quickstart/requirements.txt
  metadata-ingestion-modules/airflow-plugin/build.gradle
Labels: devops, ingestion

#117 Splitting up groups by "/" delimiter
  datahub-frontend/app/auth/sso/oidc/OidcCallbackLogic.java
Labels: product

#119 feat(ui): multiple frontend changes
  datahub-web-react/src/app/entity/dataset/preview/Preview.tsx
  datahub-web-react/src/app/preview/DefaultPreviewCard.tsx
Labels: product

#120 add new data source type: app
  datahub-web-react/src/app/create/Components/CsvForm.tsx
Labels: product

#121 update to use openjdk-17. openjdk-11 is not available in the debian repo
  docker/datahub-ingestion-base/Dockerfile
Labels: devops
