Repository aqden/datahub, pull requests merged in 2023-11, with the labels that each got.

#135 feat(gms): store update events in a new index in ElasticSearch
  docker/elasticsearch-setup/create-indices.sh
  metadata-io/src/main/java/com/linkedin/metadata/search/EntitySearchService.java
  metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/ElasticSearchService.java
  metadata-io/src/main/java/com/linkedin/metadata/search/elasticsearch/update/ESWriteDAO.java
  metadata-io/src/main/java/com/linkedin/metadata/search/transformer/SearchDocumentTransformer.java
  metadata-io/src/main/java/com/linkedin/metadata/search/utils/SearchUtils.java
  metadata-jobs/mae-consumer/src/main/java/com/linkedin/metadata/kafka/hook/UpdateIndicesHook.java
  metadata-service/restli-servlet-impl/src/main/resources/index/usage-event/update_event_template.json
Labels: product, devops

#134 feat(metadata-ingestions) logs for openapi plugin
  metadata-ingestion/src/datahub/ingestion/source/openapi.py
  metadata-ingestion/src/datahub/ingestion/source/openapi_parser.py
Labels: ingestion

#136 feat(datahub-web-react) add new data platform option for csv form
  datahub-web-react/src/app/create/Components/CsvForm.tsx
Labels: product
